"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 23:38:20.875369
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('waba_id', sa.String(length=64), nullable=True),
    sa.Column('phone_number_id', sa.String(length=64), nullable=True),
    sa.Column('business_manager_id', sa.String(length=64), nullable=True),
    sa.Column('onboarding_status', sa.Enum('kickoff', 'bm_verification', 'number_provisioning', 'webhook_setup', 'template_submission', 'optin_test', 'go_live', 'live', name='onboarding_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('jira_epic_key', sa.String(length=32), nullable=True),
    sa.Column('go_live_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_phone_number_id'), 'clients', ['phone_number_id'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('hubspot_id', sa.String(length=64), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('opt_in_status', sa.Enum('opted_in', 'opted_out', 'pending', name='opt_in_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('opt_in_source', sa.Enum('qr', 'keyword', 'api', name='opt_in_source', native_enum=False, create_constraint=True, length=32), nullable=True),
    sa.Column('opt_in_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gdpr_consent', sa.Boolean(), nullable=False),
    sa.Column('gdpr_consent_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'phone_e164', name='uq_contact_client_phone')
    )
    op.create_index(op.f('ix_contacts_client_id'), 'contacts', ['client_id'], unique=False)
    op.create_table('onboarding_checklists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('step_name', sa.String(length=100), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'done', 'blocked', name='checklist_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'step_order', name='uq_checklist_client_order')
    )
    op.create_index(op.f('ix_onboarding_checklists_client_id'), 'onboarding_checklists', ['client_id'], unique=False)
    op.create_table('wa_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('language', sa.Enum('en_GB', 'de_DE', name='template_language', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('category', sa.Enum('utility', 'marketing', 'authentication', name='template_category', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('header_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'rejected', name='template_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('meta_template_id', sa.String(length=64), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('extras_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'name', 'language', name='uq_template_client_name_lang')
    )
    op.create_index(op.f('ix_wa_templates_client_id'), 'wa_templates', ['client_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('booking_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', 'no_show', 'rescheduled', name='appointment_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('reminder_sent_24h', sa.Boolean(), nullable=False),
    sa.Column('confirmation_template_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_booking_time'), 'appointments', ['booking_time'], unique=False)
    op.create_index(op.f('ix_appointments_client_id'), 'appointments', ['client_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('wamid', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.Enum('in', 'out', name='message_direction', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('type', sa.Enum('text', 'template', 'button', name='message_type', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('sent', 'delivered', 'read', 'failed', name='message_status', native_enum=False, create_constraint=True, length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wamid')
    )
    op.create_index(op.f('ix_messages_client_id'), 'messages', ['client_id'], unique=False)
    op.create_index('ix_messages_contact_ts', 'messages', ['contact_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_contact_ts', table_name='messages')
    op.drop_index(op.f('ix_messages_client_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_appointments_client_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_booking_time'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_wa_templates_client_id'), table_name='wa_templates')
    op.drop_table('wa_templates')
    op.drop_index(op.f('ix_onboarding_checklists_client_id'), table_name='onboarding_checklists')
    op.drop_table('onboarding_checklists')
    op.drop_index(op.f('ix_contacts_client_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_clients_phone_number_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
